version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    tty: true
    env_file:
      - ./docker/db/db-variables.env

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "50000:3300"
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
      - ./docker/db/mysql_data:/var/lib/mysql
    env_file:
      - ./docker/db/db-variables.env
